### ISSUE TITLE
Unable to build libbtc.a

### ISSUE THREAD

**Issue by 0xD3adC0d3** [libbtc/libbtc#110]
Hello Jonas,

First of all, thank you very much for your work. It is exactly what I want to use in my project.

Unfortunately, when I run the commands to build (http://libbtc.github.io/docs/guides/build-and-link/), I do obtain executable tools but not the library itself.

A libbtc.la file is generated but not the libbtc.a or .so I would need. Could you please advise?

Thank you in advance for your support!
Best regards,

0xD3adC0d3

**Comment by 0xD3adC0d3** [comment]
Sorry, I forgot to mention: I'm working on Debian

**Comment by jonasschnelli** [comment]
If you need the static .a, have you tried the enable static builds by using `./configure --enable-static`?

**Comment by 0xD3adC0d3** [comment]
I didn't think about it before. 
I just tried and have the same result. No libbtc.a file in any directory

**Comment by jonasschnelli** [comment]
Works on my end... (just tested on Debian).
Have you looked in the `/.libs` folder?

```shell
git clone https://github.com/libbtc/libbtc
cd libbtc/
./autogen.sh
./configure --enable-static
make -j5
 ls .libs/

libbtc.a  libbtc.la  libbtc.lai
```

**Comment by 0xD3adC0d3** [comment]
Yeah it works, I didn't know about the .libs directory.

Thank you very much for your help! :)
