### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by AtsukiTak** [libbtc/libbtc#122]
I'm not 100% sure that these are typos. Just notification.

https://github.com/libbtc/libbtc/blob/master/include/btc/net.h#L145
s/nodex/nodes

https://github.com/libbtc/libbtc/blob/master/src/memory.c#L91
s/btc_malloc/btc_calloc

https://github.com/libbtc/libbtc/blob/master/src/memory.c#L105
s/calloc/realloc
s/btc_malloc/btc_realloc

**Comment by AtsukiTak** [comment]
https://github.com/libbtc/libbtc/blob/master/include/btc/net.h#L117
s/group/node

**Comment by jonasschnelli** [comment]
Yes. There are probably more typos...
Are you willing to fix them in with a pull request?
