### ISSUE TITLE
Ripemd160 function is not `extern "C"`

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [libbtc/libbtc#141]
I'm not sure whether this is intended or not, but the function `ripemd160()` in its header file doesn't have `extern "C"` declared, which causes name mangling problems. I can fix this myself, but I need to understand the intentions behind this, if any. What I'm using `ripemd160` for is basically creating an address from a redeem script. This functionality doesn't seem to be available in libbtc without segwit.

**Comment by xloem** [comment]
I think this was posted in error.  My system is showing me that ripemd160.h was wrapped with `LIBBTC_BEGIN_DECL` and `LIBBTC_END_DECL` when it was created in 15ac927fc1bb7a3dc49f812dc237edcbc68eaa0b .  These macros are defined to `extern "C" {` `}`} in btc.h when compiling under c++.
