### ISSUE TITLE
Remove assert()

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [libbtc/libbtc#148]
In C++ (at least), assert is not the identity function in release mode. It's simply not called at all. This ruined many things the program does, including generating private keys. This is very, very dangerous as it could generate invalid private keys.

**Comment by TheQuantumPhysicist** [comment]
Discussed here: https://stackoverflow.com/questions/52117904/does-assert-act-as-the-identity-function-in-release-mode

**Comment by xloem** [comment]
Fixed by #142
