### ISSUE TITLE
Loading wallet failed

### ISSUE THREAD

**Issue by CryptoCoinLab** [libbtc/libbtc#161]
Run bitcoin-spv under macOS 10.15,  when I run bitcoin-spv the second time, it failed with a wrong private key and an error message saying "Loading wallet failed".

this is the correct xpriv
xpriv: xprv9s21ZrQH143K2bPFpDfPLtYjq6DxzthDdwSRB8FmX67JgMm13Nehrvr8tVwDCGhsrajEPAm1dAChoYLXHmVCdFgoy7TePg9ehg7WddEmaDs

the following is the wrong one 
xpriv: xprv9s21ZrQH143K2bPFpDfPLtYjq6DxzthDdwSRB8FmX67JgMm13Nehrvr8tVwDCGhsrajEPAm1dAChoYLXHmVCdFgoy7TePg9ehg7WddEmaDsd

so I corrected in wallet.c line 348

char strbuf[196]; 
memset(strbuf,0,196);  // this line should be added.
if (!deser_varlen_from_file(&len, wallet->dbfile)) return false;

now it is ok to run bitcoin-spv any times.

**Comment by jsarenik** [comment]
Thanks for reporting this!

**Comment by jsarenik** [comment]
Your patch a bit more machine-readable here:

```C
diff --git a/src/wallet.c b/src/wallet.c
index d6ee528..656dc48 100644
--- a/src/wallet.c
+++ b/src/wallet.c
@@ -346,6 +346,7 @@ btc_bool btc_wallet_load(btc_wallet* wallet, const char* file_path, int *error,
             if (rectype == WALLET_DB_REC_TYPE_MASTERKEY) {
                 uint32_t len;
                 char strbuf[196];
+                memset(strbuf, 0, 196);
                 if (!deser_varlen_from_file(&len, wallet->dbfile)) return false;
                 if (len > sizeof(strbuf)) { return false; }
                 if (fread(strbuf, len, 1, wallet->dbfile ) != 1) return false;

```

**Comment by CryptoCoinLab** [comment]
yes, you are right. And thank you for developing libbtc, good job.

**Comment by jsarenik** [comment]
@CryptoCoinLab could you please send a PR for this so that the change can be commited in your name and hopefully others may come with feed-back… Thank you!

**Comment by jsarenik** [comment]
@CryptoCoinLab see the PR done with your authorship: https://github.com/jsarenik/libbtc/pull/1
