### ISSUE TITLE
Miscalculated NULL termination

### ISSUE THREAD

**Issue by yellowjackets200** [libbtc/libbtc#49]
In file `utils.c`, function `utils_bin_to_hex()`, the following line writes NULL in a memory location beyond the array bound, resulting in an Abort trap 6 error while running the tests.

`hex_out[inlen * 2] = '\0'`

The array's size should be incremented to include NULL termination.

**Comment by jonasschnelli** [comment]
Thanks for opening this issue.
You right,... i'll try to work on a fix.
