### ISSUE TITLE
 fatal error: 'logdb/cstr.h' file not found

### ISSUE THREAD

**Issue by ChristopherA** [libbtc/libbtc#53]
When compiling on a Mac (current El Capitan 10.11.6), ./configure results in this warning
````
=== configuring in src/logdb (/Users/ChristopherA/projects/libbtc/src/logdb)
configure: WARNING: no configuration information is in src/logdb
````
When doing make results in:
````
  CC       src/libbtc_la-block.lo
In file included from src/block.c:32:
In file included from ./include/btc/block.h:14:
./include/btc/hash.h:41:10: fatal error: 'logdb/cstr.h' file not found
#include <logdb/cstr.h>
         ^
1 error generated.
make[1]: *** [src/libbtc_la-block.lo] Error 1
make: *** [all-recursive] Error 1
````

**Comment by jonasschnelli** [comment]
Thanks for reporting.
`liblogdb` is currently included over a git submodule.
You need to init the submodules first:

```
git submodule init
git submodule update
```

Then it will need again a `./autogen.sh` and a `./configure`.


The whole mixture between libbtc and liblogdb is a mess. I really need to change the way libbtc depends on liblogdb by just including some files directly.

**Comment by jonasschnelli** [comment]
Current master does now no longer depend on liblogdb over submodule. It's directly included now.
Closing.
