### ISSUE TITLE
support for p2sh

### ISSUE THREAD

**Issue by samnet** [libbtc/libbtc#56]
Hello dear J!
i m interested in bitcoin on embedded device and your library looks great.
Does it support p2sh spend transactions?
Is there any documentation regarding how to create and sign transactions using libbtc?
Kind regards,

**Comment by jonasschnelli** [comment]
Yes. This is possible...
You could do something like:
```c

    //create new transaction
    btc_tx* tx = btc_tx_new();

    //add p2sh output of 1000 satoshis
    btc_tx_add_address_out(tx, &btc_chain_main, 1000, "3F8mnK21uCqHuQ8QJ27MEyt6YvBoouRtWg"); //a P2SH address

    //add some inputs
    // ...
    
    // get raw transaction
    cstring *txser = cstr_new_sz(1024);
    btc_tx_serialize(txser, tx);
    char hexbuf[txser->len * 2 + 1];
    utils_bin_to_hex((unsigned char*)txser->str, txser->len, hexbuf);

    //cleanup
    btc_tx_free(tx);
```

**Comment by samnet** [comment]
Thanks for this reply. 
This seems like a tx to **fund** a p2sh however. 
I mostly interested in **spending** a p2sh. 
Some libraries are able to do the first, but not hte second (e.g., bitcoinJ). Is libbtc able to do the spend p2sh (and if yes, how, please?)?

The bit of code you posted is nevertheless very useful anyways since they give an entry point to using the library. In it, you used a hardcoded 3 address.... but has the library some function to build p2sh scripts? 

Thank you

**Comment by jonasschnelli** [comment]
Yes. This should work as well.

```c
// fill your binary redeem script into a cstring
cstring* script = cstr_new_buf(redeemscript_byte_array, redeemscript_length);

// set the index of the input (position)
int inputindex = 0

//get the hash for signing of a input (can be a p2sh input)
uint8_t sighash[32];
btc_tx_sighash(tx, script, inputindex, SIGHASH_ALL, sighash);

// your hash for signing should be in sighash
// now you need to sign the hash, check eckey_tests.c
// something like: btc_key_sign_hash(&key, hash, sig, &outlen);

**Comment by samnet** [comment]
Thank you. Looks like a great library. 
Before closing this issue, is there a documentation / howto for it?
Thanks

**Comment by jonasschnelli** [comment]
> Before closing this issue, is there a documentation / howto for it?

unfortunately no. I'd like to write a proper documentation soon (which I think is one of the most important things for a library).

**Comment by samnet** [comment]
Thx
