### ISSUE TITLE
GMP dependency (undefined reference "__gmpn_*")

### ISSUE THREAD

**Issue by muxcoin** [libbtc/libbtc#69]
It's possible I missed something, but the (very small) documentation claims the only dependency is libevent if the networking library is used. I noticed I had to link in libgmp (GMP) also to resolve _gmpn* undefined reference errors. Was there a misconfiguration on my part or was the documentation not accurate? Also the examples references "ecc_start()" and "ecc_stop()" functions but those functions appear to be defined as "btc_ecc_start()" and "btc_ecc_stop()". thanks

**Comment by jonasschnelli** [comment]
GMP is optional IMO.
Maybe you have configured in a env where GMP was available but then compiled where it wasn't?

https://github.com/bitcoin-core/secp256k1/blob/9d560f992db26612ce2630b194aef5f44d63a530/configure.ac#L283
