### ISSUE TITLE
Additional build notes needed for README.md

### ISSUE THREAD

**Issue by ChristopherA** [libbtc/libbtc#95]
When I install this on a minimal Debian 8-based machine (chosen for more security as opposed to my normal Macintosh development environment) the short 3-step build instructions in the README.md are incomplete.

In my case I needed to  also install some non-default development tools `sudo apt-get install autoconf libtool libevent-dev`. Quite possibly there are some other tools that are required but I installed previously. The README.md should probably list any toolchain dependencies.

**Comment by tomryanx** [comment]
On OpenBSD, `autoconf` `automake` `libtool` `libevent`, and possibly `libeventextra` all need to be installed. Configure doesn't find /usr/local/include/event2/event.h by itself, either.

**Comment by grr** [comment]
On Darwin with MacPorts, configure should be checking `/opt/local`, but the user has to force this with: `CFLAGS='-I/opt/local/include' CPPFLAGS='-I/opt/local/include' LDFLAGS='-L/opt/local/lib' ./configure`. Even so, the linker fails on `bitcoin-spv` with undefined symbols.

**Comment by xloem** [comment]
These are all very basic things: a compiler and libevent.  But I made #168: is it correct?
@grr your issue looks like a build system issue rather than a readme issue.  The code is currently building fine on travis's osx image without any special config: are you still having your issue?
