### ISSUE TITLE
Can I use this for other currencies?

### ISSUE THREAD

**Issue by punto-** [libbtc/libbtc#98]
Hi, I'm working on a system that needs to support multiple coins, can I use this to generate keys and transactions for currencies other than bitcoin? has it been tested on the ones that use the same address or transaction formats? (I only need to generate the address and sign transactions, the rest is provided by outside services, like a multi currency "light wallet" that connects to a blockchain explorer). thanks.

**Comment by jonasschnelli** [comment]
I don't know much about altcoins. Libbtc focuses on bitcoin. If you altcoin uses secp256k1 ECDSA and the same address format (which would be really a non-sende) then it would work.
But you may be able to reuse the primitives (bip32, ECDSA stuff).

**Comment by xloem** [comment]
I've had luck using this on chains similar to bitcoin by simply providing different [`btc_chainparams` data](https://github.com/libbtc/libbtc/blob/master/src/chainparams.c#L29).  You can find these values in the source code of the altcoin clients.  But if the altcoin changes from bitcoin too much, it will not work unless somebody adds the features used.  

I'm curious what altcoins people would want (and how much they differ from bitcoin), but I am closing this question for now as answered.
